# Generated by Django 5.1.5 on 2025-03-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_instructorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrollment_end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='enrollment_limit',
        ),
        migrations.RemoveField(
            model_name='course',
            name='enrollment_start_date',
        ),
    ]
