# Generated by Django 5.1.5 on 2025-03-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_learnerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
